// <autogenerated>
//   This file was generated by T4 code generator Template.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System;

namespace TianYu.Admin.Domain.ViewModel.Response
{
    /// <summary>
    /// 部门模型
    /// </summary>
    public class SystemSectionResponseModel
    {
        ///<summary>
        /// Id
        ///</summary>
        public int Id { get; set; }
        ///<summary>
        /// 父级ID
        ///</summary>
        public int ParentId { get; set; }
        ///<summary>
        /// 部门名称
        ///</summary>
        public string Name { get; set; }
        ///<summary>
        /// 部门编号
        ///</summary>
        public string Code { get; set; }
        ///<summary>
        /// 排序
        ///</summary>
        public int Sort { get; set; }
        /// <summary>
        /// 层级
        /// </summary>
        public int Level { get; set; }
    }
    /// <summary>
    /// 部门列表查询响应模型
    /// </summary>
    public class QuerySystemSectionResponseModel : SystemSectionResponseModel
    {
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime CreateTime { get; set; }
        /// <summary>
        /// 更新时间
        /// </summary>
        public DateTime ModifyTime { get; set; }
        /// <summary>
        /// 描述
        /// </summary>
        public string Remark { get; set; }
    }
    /// <summary>
    /// 部门详情查询响应模型
    /// </summary>
    public class QueryDetailSystemSectionResponseModel : SystemSectionResponseModel
    {
        /// <summary>
        /// 描述
        /// </summary>
        public string Remark { get; set; }
    }
}

