// <autogenerated>
//   This file was generated by T4 code generator Template.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System;
using System.Collections.Generic;

namespace TianYu.Admin.Domain.ViewModel.Response
{
    /// <summary>
    /// 菜单模型
    /// </summary>
    public class SystemMenuResponseModel
    {
        ///<summary>
        /// Id
        ///</summary>
        public int Id { get; set; }
        ///<summary>
        /// 菜单名称
        ///</summary>
        public string MenuName { get; set; }
        ///<summary>
        /// 菜单描述
        ///</summary>
        public string MenuDesc { get; set; }
        ///<summary>
        /// 菜单图标
        ///</summary>
        public string MenuIcon { get; set; }
        ///<summary>
        /// 菜单Url
        ///</summary>
        public string MenuUrl { get; set; }
        ///<summary>
        /// 父级ID(-1为顶级)
        ///</summary>
        public int ParentId { get; set; }
        /// <summary>
        /// 父级名称
        /// </summary>
        public string ParentName { get; set; }
        ///<summary>
        /// 是否启用
        ///</summary>
        public bool Enabled { get; set; }
        ///<summary>
        /// 菜单按钮
        ///</summary>
        public string MenuButtonId { get; set; }
        ///<summary>
        /// 层级
        ///</summary>
        public int? Level { get; set; }
        ///<summary>
        /// 排序
        ///</summary>
        public int MenuSort { get; set; }
        ///<summary>
        /// 创建时间
        ///</summary>
        public DateTime CreateTime { get; set; }
        ///<summary>
        /// 修改时间
        ///</summary>
        public DateTime ModifyTime { get; set; }
        ///<summary>
        /// 菜单编码
        ///</summary>
        public int MenuCode { get; set; }
        ///<summary>
        /// 父级编码
        ///</summary>
        public int? ParentCode { get; set; }
    }
    /// <summary>
    /// 菜单列表查询响应模型
    /// </summary>
    public class QuerySystemMenuResponseModel : SystemMenuResponseModel
    {
        ///<summary>
        /// 菜单按钮名称
        ///</summary>
        public string MenuButtonName { get; set; }
    }
    /// <summary>
    /// 菜单详情查询响应模型
    /// </summary>
    public class QueryDetailSystemMenuResponseModel : SystemMenuResponseModel
    {
        /// <summary>
        /// 操作按钮
        /// </summary>
        public IList<SystemButton> ButtonList { get; set; }
    }
    /// <summary>
    /// 系统按钮
    /// </summary>
    public class SystemButton
    {
        ///<summary>
        /// Id
        ///</summary>
        public int Id { get; set; }
        ///<summary>
        /// 按键名称
        ///</summary>
        public string ButtonName { get; set; }
        ///<summary>
        /// 按键代码
        ///</summary>
        public string ButtonCode { get; set; }
        ///<summary>
        /// 是否启用
        ///</summary>
        public bool Checked { get; set; } = false;
        ///<summary>
        /// 排序
        ///</summary>
        public int Sort { get; set; }
    }

}

