// <autogenerated>
//   This file was generated by T4 code generator Template.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

 
using System;
using TianYu.Admin.Infrastructure.Enum;
using TianYu.Core.Common;

namespace TianYu.Admin.Domain.ViewModel.Response
{
    /// <summary>
    /// 系统账号模型
    /// </summary>
    public class SystemStaffResponseModel
    {
                ///<summary>
        /// Id
        ///</summary>
        public int Id { get; set; }
        ///<summary>
        /// 登录名称
        ///</summary>
        public string LoginName { get; set; }
        ///<summary>
        /// 登录密码
        ///</summary>
        public string LoginPwd { get; set; }
        ///<summary>
        /// 盐值
        ///</summary>
        public string MaskCode { get; set; }
        ///<summary>
        /// 手机
        ///</summary>
        public string Mobile { get; set; }
        ///<summary>
        /// 电话
        ///</summary>
        public string Tel { get; set; }
        ///<summary>
        /// 邮箱
        ///</summary>
        public string Eamil { get; set; }
        ///<summary>
        /// 呢称
        ///</summary>
        public string NickName { get; set; }
        ///<summary>
        /// 状态：0有效，1禁用
        ///</summary>
        public SystemStaffStatus Status { get; set; }
        /// <summary>
        /// 状态：0有效，1禁用
        /// </summary>
        public string StatusText => Status.GetEnumDescription();
        ///<summary>
        /// 所属部门
        ///</summary>
        public string SectionId { get; set; }
        ///<summary>
        /// 最近登录时间
        ///</summary>
        public DateTime? LastLoginTime { get; set; }
        ///<summary>
        /// 创建时间
        ///</summary>
        public DateTime CreateTime { get; set; }
        ///<summary>
        /// 修改时间
        ///</summary>
        public DateTime ModifyTime { get; set; }
    }
    /// <summary>
    /// 系统账号列表查询响应模型
    /// </summary>
    public class QuerySystemStaffResponseModel: SystemStaffResponseModel
    {
        /// <summary>
        /// 角色名称
        /// </summary>
        public string RoleName { get; set; }
        ///<summary>
        /// 所属部门
        ///</summary>
        public string SectionName { get; set; }
    }
    /// <summary>
    /// 系统账号详情查询响应模型
    /// </summary>
    public class QueryDetailSystemStaffResponseModel: SystemStaffResponseModel
    {  
    }
}

