// <autogenerated>
//   This file was generated by T4 code generator Template.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

 
using System; 

namespace TianYu.Admin.Domain.ViewModel.Response
{
    /// <summary>
    /// 账号角色模型
    /// </summary>
    public class SystemStaffRoleResponseModel
    { 
        ///<summary>
        /// 用户Id
        ///</summary>
        public int StaffId { get; set; }
        ///<summary>
        /// 角色Id
        ///</summary>
        public int RoleId { get; set; }
    }
    /// <summary>
    /// 账号角色列表查询响应模型
    /// </summary>
    public class QuerySystemStaffRoleResponseModel: SystemStaffRoleResponseModel
    { 
    }
    /// <summary>
    /// 账号角色详情查询响应模型
    /// </summary>
    public class QueryDetailSystemStaffRoleResponseModel: SystemStaffRoleResponseModel
    {  
    }
}

