// <autogenerated>
//   This file was generated by T4 code generator Template.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

 
using System; 

namespace TianYu.Admin.Domain.ViewModel.Response
{
    /// <summary>
    /// 角色权限表模型
    /// </summary>
    public class SystemRolePowerResponseModel
    {
                ///<summary>
        /// Id
        ///</summary>
        public int Id { get; set; }
        ///<summary>
        /// 后台角色Id
        ///</summary>
        public int SystemRoleId { get; set; }
        ///<summary>
        /// 后台权限Id
        ///</summary>
        public int SystemPowerId { get; set; }
    }
    /// <summary>
    /// 角色权限表列表查询响应模型
    /// </summary>
    public class QuerySystemRolePowerResponseModel: SystemRolePowerResponseModel
    { 
    }
    /// <summary>
    /// 角色权限表详情查询响应模型
    /// </summary>
    public class QueryDetailSystemRolePowerResponseModel: SystemRolePowerResponseModel
    {  
    }
}

