// <autogenerated>
//   This file was generated by T4 code generator Template.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

 
using System; 

namespace TianYu.Admin.Domain.ViewModel.Response
{
    /// <summary>
    /// 权限项模型
    /// </summary>
    public class SystemPowerItemResponseModel
    {
                ///<summary>
        /// Id
        ///</summary>
        public int Id { get; set; }
        ///<summary>
        /// 上级Id
        ///</summary>
        public string ParentCode { get; set; }
        ///<summary>
        /// 权限项编码（ 每个层级占3位）
        ///</summary>
        public string PowerCode { get; set; }
        ///<summary>
        /// 权限项名称
        ///</summary>
        public string PowerName { get; set; }
        ///<summary>
        /// 图标
        ///</summary>
        public string IconCode { get; set; }
        ///<summary>
        /// 项目模块
        ///</summary>
        public string BussionModule { get; set; }
        ///<summary>
        /// 地址（route/controller/action 或 controller/action ）
        ///</summary>
        public string ActionUrl { get; set; }
        ///<summary>
        /// 排序编号
        ///</summary>
        public int? SortCode { get; set; }
        ///<summary>
        /// 描述
        ///</summary>
        public string Remark { get; set; }
        ///<summary>
        /// 状态(0=禁用，1=启用)
        ///</summary>
        public int Status { get; set; }
        ///<summary>
        /// 创建时间
        ///</summary>
        public DateTime CreateTime { get; set; }
        ///<summary>
        /// 更新时间
        ///</summary>
        public DateTime UpdateTime { get; set; }
        ///<summary>
        /// 等级
        ///</summary>
        public int? Level { get; set; }
        ///<summary>
        /// 系统名称
        ///</summary>
        public string SystemName { get; set; }
    }
    /// <summary>
    /// 权限项列表查询响应模型
    /// </summary>
    public class QuerySystemPowerItemResponseModel: SystemPowerItemResponseModel
    { 
    }
    /// <summary>
    /// 权限项详情查询响应模型
    /// </summary>
    public class QueryDetailSystemPowerItemResponseModel: SystemPowerItemResponseModel
    {  
    }
}

