// <autogenerated>
//   This file was generated by T4 code generator Template.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

 
using System; 

namespace TianYu.Admin.Domain.ViewModel.Response
{
    /// <summary>
    /// 角色权限模型
    /// </summary>
    public class SystemRoleRulesResponseModel
    {
                ///<summary>
        /// ID
        ///</summary>
        public int Id { get; set; }
        ///<summary>
        /// 角色ID
        ///</summary>
        public int RoleId { get; set; }
        ///<summary>
        /// 菜单ID
        ///</summary>
        public int MenuId { get; set; }
        ///<summary>
        /// 按键ID
        ///</summary>
        public int ButtonId { get; set; }
    }
    /// <summary>
    /// 角色权限列表查询响应模型
    /// </summary>
    public class QuerySystemRoleRulesResponseModel: SystemRoleRulesResponseModel
    { 
    }
    /// <summary>
    /// 角色权限详情查询响应模型
    /// </summary>
    public class QueryDetailSystemRoleRulesResponseModel: SystemRoleRulesResponseModel
    {  
    }
}

