// <autogenerated>
//   This file was generated by T4 code generator Template.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using TianYu.Core.Common;
using TianYu.Admin.Service.IService;
using System.Web.Mvc;
using TianYu.Core.Common.FilterAttribute.Mvc;
using TianYu.Admin.Domain.ViewModel.Request;
using TianYu.Admin.Domain.ViewModel.Response;
using System.Collections.Generic;
using System.Linq;

namespace TianYu.Admin.WebMvc.Controllers
{
    /// <summary>
    /// 部门控制器
    /// </summary>
    [MvcLoginFilter]
    public class SystemSectionController : BaseController
    {
        private ISystemSectionService _systemSectionService = null;
        public SystemSectionController(ISystemSectionService systemSectionService)
        {
            this._systemSectionService = systemSectionService;
        }


        /// <summary>
        /// 列表
        /// </summary>
        /// <returns></returns> 
        public ActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// 新增
        /// </summary>
        /// <returns></returns>  
        public ActionResult Add(int pId, string pCode, string pName)
        {
            ViewBag.pCode = pCode;
            ViewBag.pName = pName;
            ViewBag.pId = pId;

            return View();
        }
        /// <summary>
        /// 编辑
        /// </summary> 
        /// <returns></returns> 
        public ActionResult Edit(QueryDetailSystemSectionRequestModel requestModel)
        {
            var res = _systemSectionService.QueryDetail(requestModel);

            if (res != null && res.BusinessData != null)
            {
                if (res.BusinessData.ParentId == 0)
                {
                    ViewBag.pName = "顶级";
                }
                else
                {
                    requestModel.Id = res.BusinessData.ParentId;

                    var entity = _systemSectionService.QueryDetail(requestModel);

                    ViewBag.pName = entity.BusinessData.Name;
                }
            }

            return View(res.BusinessData);
        }


        /// <summary>
        /// 获取
        /// </summary>
        /// <param name="requestModel"></param>
        /// <returns></returns>
        public ActionResult Query(QuerySystemSectionRequestModel requestModel)
        {
            var res = _systemSectionService.Query(requestModel);
            return Content(res.ToJsonString());
        }
        /// <summary>
        /// 添加
        /// </summary>
        /// <param name="requestModel"></param>
        /// <returns></returns>
        public ActionResult Insert(AddSystemSectionRequestModel requestModel)
        {
            var ret = _systemSectionService.Insert(requestModel);
            return Content(ret.ToJsonString());
        }
        /// <summary>
        /// 修改
        /// </summary>
        /// <param name="requestModel"></param>
        /// <returns></returns>
        public ActionResult Update(UpdateSystemSectionRequestModel requestModel)
        {
            var ret = _systemSectionService.Update(requestModel);
            return Content(ret.ToJsonString());
        }
        /// <summary>
        /// 删除
        /// </summary>
        /// <param name="requestModel"></param>
        /// <returns></returns>
        public ActionResult Remove(RemoveSystemSectionRequestModel requestModel)
        {
            var ret = _systemSectionService.Remove(requestModel);
            return Content(ret.ToJsonString());
        }
    }
}
