// <autogenerated>
//   This file was generated by T4 code generator Template.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

  
using System;
using System.ComponentModel.DataAnnotations;
using TianYu.Core.Common.BaseViewModel; 

namespace TianYu.Admin.Domain.ViewModel.Request
{
    /// <summary>
    /// 数据字典模型
    /// </summary>
    public class SystemDictionaryRequestModel
    { 
                ///<summary>
        /// Id
        ///</summary>
        public int Id { get; set; }
        ///<summary>
        /// 父级ID（第一级为0）
        ///</summary>
        public int ParentId { get; set; }
        ///<summary>
        /// 字典编码
        ///</summary>
        public string Code { get; set; }
        ///<summary>
        /// 字典名称
        ///</summary>
        public string Name { get; set; }
        ///<summary>
        /// 字典描述
        ///</summary>
        public string Remark { get; set; }
        ///<summary>
        /// 字典值
        ///</summary>
        public string Value { get; set; }
        ///<summary>
        /// 排序
        ///</summary>
        public int? Sort { get; set; }
        ///<summary>
        /// 创建时间
        ///</summary>
        public DateTime CreateTime { get; set; }
        ///<summary>
        /// 修改时间
        ///</summary>
        public DateTime ModifyTime { get; set; }
    }


    /// <summary>
    /// 添加数据字典请求模型
    /// </summary>
    public class AddSystemDictionaryRequestModel: SystemDictionaryRequestModel
    {

    }
    /// <summary>
    /// 修改数据字典请求模型
    /// </summary>
    public class UpdateSystemDictionaryRequestModel: SystemDictionaryRequestModel
    {
        ///<summary>
        /// Id
        ///</summary>
        public int Id { get; set; }
    }
    /// <summary>
    /// 删除数据字典请求模型
    /// </summary>
    public class RemoveSystemDictionaryRequestModel
    {
        ///<summary>
        /// Id
        ///</summary>
        public int Id { get; set; }
    }
    /// <summary>
    /// 查询数据字典列表请求模型
    /// </summary>
    public class QuerySystemDictionaryRequestModel : ApiBasePageRequestModel
    {
	    /// <summary>
        /// 查询关键字
        /// </summary>
        public string KeyWord { get; set; }
    }
    /// <summary>
    /// 查询数据字典详情请求模型
    /// </summary>
    public class QueryDetailSystemDictionaryRequestModel :ApiBaseRequestModel
    {

    }
}

