// <autogenerated>
//   This file was generated by T4 code generator Template.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

 
using System;
using System.Data.Entity;
using System.Collections.Generic;
using TianYu.Admin.Domain;
using TianYu.Admin.Domain.Mapping;

namespace TianYu.Admin.Domain
{
    public partial class TianYuSystemPowerContext : DbContext
    {
        static TianYuSystemPowerContext()
        {
            Database.SetInitializer<TianYuSystemPowerContext>(null);
        }
        public TianYuSystemPowerContext()
            : base("Name=TianYuSystemPowerContext")
        { }

        public TianYuSystemPowerContext(string nameOrConnectionString)
            : base(nameOrConnectionString)
        { }
		 
		  		public virtual DbSet<SystemDictionary> SystemDictionarys { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        { 
						modelBuilder.Configurations.Add(new SystemDictionaryMap()); 

        }
    }
}
