// <autogenerated>
//   This file was generated by T4 code generator Template.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

 
using TianYu.Core.Common.BaseEF;
using TianYu.Admin.Domain;

namespace TianYu.Admin.Repository.IModelRepository
{ 
    /// <summary> 
	/// 按键仓储接口类
	/// </summary> 
    public partial interface ISystemActionButtonRepository :IEFBaseRepository<SystemActionButton>
    {

    }
}

