// <autogenerated>
//   This file was generated by T4 code generator Template.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

 
using TianYu.Core.Common.BaseEF;
using TianYu.Admin.Domain;

namespace TianYu.Admin.Repository.IModelRepository
{ 
    /// <summary> 
	/// 角色权限仓储接口类
	/// </summary> 
    public partial interface ISystemRoleRulesRepository :IEFBaseRepository<SystemRoleRules>
    {

    }
}

