// <autogenerated>
//   This file was generated by T4 code generator Template.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System.Collections.Generic;
using System.Linq;
using TianYu.Admin.Domain.ViewModel.Response;
using TianYu.Admin.Repository.IModelRepository;
using TianYu.Admin.Service.IService;
using TianYu.Core.Common;

namespace TianYu.Admin.Service.Service
{
    /// <summary> 
	/// 账号角色仓储服务类
	/// </summary> 
    public class SystemStaffRoleService : ISystemStaffRoleService
    {
        private readonly ISystemStaffRoleRepository _systemStaffRoleRepository;
        public SystemStaffRoleService(ISystemStaffRoleRepository systemStaffRoleRepository)
        {
            this._systemStaffRoleRepository = systemStaffRoleRepository;
        }
        /// <summary>
        /// 查询员工角色
        /// </summary>
        /// <param name="staffId"></param>
        /// <returns></returns>
        public IList<QuerySystemStaffRoleResponseModel> QueryStaffRoleByStaffId(int staffId)
        {
            var res = new List<QuerySystemStaffRoleResponseModel>();

            var query = _systemStaffRoleRepository.Find(x => x.StaffId == staffId).ToList();

            if (query.Any())
            {
                var list = query.ToList();

                res = list.MapToList<QuerySystemStaffRoleResponseModel>();
            }

            return res;
        }
    }
}



