// <autogenerated>
//   This file was generated by T4 code generator Template.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

 
using TianYu.Admin.Domain;
using TianYu.Admin.Repository.BaseRepository;
using TianYu.Admin.Repository.IModelRepository;

namespace TianYu.Admin.Repository.ModelRepository
{
    /// <summary> 
	/// 账号角色仓储类
	/// </summary> 
    public class SystemStaffRoleRepository :EFRepository<SystemStaffRole>, ISystemStaffRoleRepository
    {

    }
}


