// <autogenerated>
//   This file was generated by T4 code generator Template.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using TianYu.Admin.Domain.ViewModel;
using System.Collections.Generic;
using TianYu.Core.Common.BaseViewModel;
using TianYu.Admin.Domain.ViewModel.Request;
using TianYu.Admin.Domain.ViewModel.Response;

namespace TianYu.Admin.Service.IService
{
    /// <summary>
    /// 角色服务接口
    /// </summary>
    public interface ISystemRoleService
    {
        /// <summary>
        /// 添加
        /// </summary>
        /// <param name="requestModel"></param>
        /// <returns></returns>
        BusinessBaseViewModel<string> Insert(AddSystemRoleRequestModel requestModel);
        /// <summary>
        /// 删除
        /// </summary>
        /// <param name="requestModel"></param>
        /// <returns></returns>
        BusinessBaseViewModel<string> Remove(RemoveSystemRoleRequestModel requestModel);
        /// <summary>
        /// 修改
        /// </summary>
        /// <param name="requestModel"></param>
        /// <returns></returns>
        BusinessBaseViewModel<string> Update(UpdateSystemRoleRequestModel requestModel);
        /// <summary>
        /// 查询列表
        /// </summary>
        /// <param name="requestModel"></param>
        /// <returns></returns>
        BusinessPagedBaseViewModel<QuerySystemRoleResponseModel> Query(QuerySystemRoleRequestModel requestModel);
        /// <summary>
        /// 查询明细
        /// </summary>
        /// <param name="requestModel"></param>
        /// <returns></returns>
        BusinessBaseViewModel<QueryDetailSystemRoleResponseModel> QueryDetail(QueryDetailSystemRoleRequestModel requestModel);



        /// <summary>
        /// 获取角色
        /// </summary> 
        /// <returns></returns>
        IEnumerable<QuerySystemRoleResponseModel> GetSystemRole();
        /// <summary>
        /// 获取员工菜单权限
        /// </summary>
        /// <param name="accountId"></param>
        /// <returns></returns>
        IEnumerable<SystemMenuRoleViewModel> FindStaffMenuRole(int accountId);
        /// <summary>
        /// 获取员工角色
        /// </summary>
        /// <param name="staffIds"></param>
        /// <returns></returns>
        IEnumerable<SystemRoleViewModel> FindStaffRoleNameByStaffId(IEnumerable<int> staffIds);
        /// <summary>
        /// 获取员工按钮权限
        /// </summary>
        /// <param name="staffId"></param>
        /// <returns></returns>
        IEnumerable<SystemButtonRoleViewModel> FindStaffRoleNameByStaffId(int staffId);
        /// <summary>
        /// 查询角色菜单权限
        /// </summary>
        /// <param name="roleId"></param>
        /// <returns></returns>
        IEnumerable<SystemMenuButtonRoleViewModel> FindMenuButtonRole(int roleId);
    }
}


