// <autogenerated>
//   This file was generated by T4 code generator Template.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

 
using TianYu.Core.Common.BaseViewModel;
using TianYu.Admin.Domain.ViewModel;
using System.Collections.Generic;
using TianYu.Admin.Domain.ViewModel.Response;

namespace TianYu.Admin.Service.IService
{
    /// <summary>
    /// 按键服务接口
    /// </summary>
    public interface ISystemActionButtonService
    {
        /// <summary>
        /// 获取系统button
        /// </summary>
        /// <returns></returns>
        IEnumerable<SystemButton> GetSystemButtons();
    }
}


