// <autogenerated>
//   This file was generated by T4 code generator Template.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using TianYu.Core.Common.BaseViewModel;
using TianYu.Admin.Domain.ViewModel.Request;
using TianYu.Admin.Domain.ViewModel.Response;
using System.Collections.Generic;
using TianYu.Admin.Domain;

namespace TianYu.Admin.Service.IService
{
    /// <summary>
    /// 部门业务逻辑接口
    /// </summary>
    public interface ISystemSectionService
    {
        /// <summary>
        /// 添加
        /// </summary>
        /// <param name="requestModel"></param>
        /// <returns></returns>
        BusinessBaseViewModel<string> Insert(AddSystemSectionRequestModel requestModel);
        /// <summary>
        /// 删除
        /// </summary>
        /// <param name="requestModel"></param>
        /// <returns></returns>
        BusinessBaseViewModel<string> Remove(RemoveSystemSectionRequestModel requestModel);
        /// <summary>
        /// 修改
        /// </summary>
        /// <param name="requestModel"></param>
        /// <returns></returns>
        BusinessBaseViewModel<string> Update(UpdateSystemSectionRequestModel requestModel);
        /// <summary>
        /// 查询列表
        /// </summary>
        /// <param name="requestModel"></param>
        /// <returns></returns>
        BusinessBaseViewModel<IList<QuerySystemSectionResponseModel>> Query(QuerySystemSectionRequestModel requestModel);
        /// <summary>
        /// 查询明细
        /// </summary>
        /// <param name="requestModel"></param>
        /// <returns></returns>
        BusinessBaseViewModel<QueryDetailSystemSectionResponseModel> QueryDetail(QueryDetailSystemSectionRequestModel requestModel);

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        IList<QuerySystemSectionResponseModel> GetSystemSection();
    }
}


