// <autogenerated>
//   This file was generated by T4 code generator Template.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

 
using TianYu.Core.Common.BaseViewModel; 
using TianYu.Admin.Domain.ViewModel.Request;
using TianYu.Admin.Domain.ViewModel.Response;

namespace TianYu.Admin.Service.IService
{
    /// <summary>
    /// 权限项业务逻辑接口
    /// </summary>
    public interface ISystemPowerItemService
    { 
	    /// <summary>
        /// 添加
        /// </summary>
        /// <param name="requestModel"></param>
        /// <returns></returns>
        BusinessBaseViewModel<string> Insert(AddSystemPowerItemRequestModel requestModel); 
        /// <summary>
        /// 删除
        /// </summary>
        /// <param name="requestModel"></param>
        /// <returns></returns>
        BusinessBaseViewModel<string> Remove(RemoveSystemPowerItemRequestModel requestModel);
        /// <summary>
        /// 修改
        /// </summary>
        /// <param name="requestModel"></param>
        /// <returns></returns>
        BusinessBaseViewModel<string> Update(UpdateSystemPowerItemRequestModel requestModel);
        /// <summary>
        /// 查询列表
        /// </summary>
        /// <param name="requestModel"></param>
        /// <returns></returns>
        BusinessPagedBaseViewModel<QuerySystemPowerItemResponseModel> Query(QuerySystemPowerItemRequestModel requestModel);
        /// <summary>
        /// 查询明细
        /// </summary>
        /// <param name="requestModel"></param>
        /// <returns></returns>
        BusinessBaseViewModel<QueryDetailSystemPowerItemResponseModel> QueryDetail(QueryDetailSystemPowerItemRequestModel requestModel);

    }
}


