// <autogenerated>
//   This file was generated by T4 code generator Template.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

 
using TianYu.Core.Common.BaseViewModel;
using TianYu.Admin.Domain.ViewModel;
using System.Collections.Generic;
using TianYu.Admin.Domain.ViewModel.Response;

namespace TianYu.Admin.Service.IService
{
    /// <summary>
    /// 账号角色服务接口
    /// </summary>
    public interface ISystemStaffRoleService
    {
        /// <summary>
        /// 查询员工角色
        /// </summary>
        /// <param name="staffId"></param>
        /// <returns></returns>
        IList<QuerySystemStaffRoleResponseModel> QueryStaffRoleByStaffId(int staffId);
    }
}


