// <autogenerated>
//   This file was generated by T4 code generator Template.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

 
using TianYu.Core.Common.BaseViewModel; 
using TianYu.Admin.Domain.ViewModel.Request;
using TianYu.Admin.Domain.ViewModel.Response;

namespace TianYu.Admin.Service.IService
{
    /// <summary>
    /// 数据字典业务逻辑接口
    /// </summary>
    public interface ISystemDictionaryService
    { 
	    /// <summary>
        /// 添加
        /// </summary>
        /// <param name="requestModel"></param>
        /// <returns></returns>
        BusinessBaseViewModel<string> Insert(AddSystemDictionaryRequestModel requestModel); 
        /// <summary>
        /// 删除
        /// </summary>
        /// <param name="requestModel"></param>
        /// <returns></returns>
        BusinessBaseViewModel<string> Remove(RemoveSystemDictionaryRequestModel requestModel);
        /// <summary>
        /// 修改
        /// </summary>
        /// <param name="requestModel"></param>
        /// <returns></returns>
        BusinessBaseViewModel<string> Update(UpdateSystemDictionaryRequestModel requestModel);
        /// <summary>
        /// 查询列表
        /// </summary>
        /// <param name="requestModel"></param>
        /// <returns></returns>
        BusinessPagedBaseViewModel<QuerySystemDictionaryResponseModel> Query(QuerySystemDictionaryRequestModel requestModel);
        /// <summary>
        /// 查询明细
        /// </summary>
        /// <param name="requestModel"></param>
        /// <returns></returns>
        BusinessBaseViewModel<QueryDetailSystemDictionaryResponseModel> QueryDetail(QueryDetailSystemDictionaryRequestModel requestModel);

    }
}


