// <autogenerated>
//   This file was generated by T4 code generator Template.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using TianYu.Admin.Domain.ViewModel.Request;
using TianYu.Core.Common.BaseViewModel; 

namespace TianYu.Admin.Service.IService
{
    /// <summary>
    /// 角色权限表服务接口
    /// </summary>
    public interface ISystemRolePowerService
    {
        /// <summary>
        /// 保存权限
        /// </summary>
        /// <param name="requestModel"></param>
        /// <returns></returns>
        BusinessBaseViewModel<string> SetRolePower(SetSystemRolePowerRequestModel requestModel);
    }
}


