// <autogenerated>
//   This file was generated by T4 code generator Template.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

  
using TianYu.Core.Common.BaseViewModel;

namespace TianYu.Admin.Domain.ViewModel.Request
{
    /// <summary>
    /// 角色模型
    /// </summary>
    public class SystemRoleRequestModel
    { 
                ///<summary>
        /// Id
        ///</summary>
        public int Id { get; set; }
        ///<summary>
        /// 角色名称
        ///</summary>
        public string RoleName { get; set; }
        ///<summary>
        /// 角色编号
        ///</summary>
        public string RoleCode { get; set; }
        ///<summary>
        /// 角色描述
        ///</summary>
        public string RoleDesc { get; set; }
        ///<summary>
        /// 排序
        ///</summary>
        public int Sort { get; set; }
        ///<summary>
        /// 是否启用
        ///</summary>
        public bool Enabled { get; set; } 
    }


    /// <summary>
    /// 添加角色请求模型
    /// </summary>
    public class AddSystemRoleRequestModel: SystemRoleRequestModel
    {

    }
    /// <summary>
    /// 修改角色请求模型
    /// </summary>
    public class UpdateSystemRoleRequestModel: SystemRoleRequestModel
    {
        ///<summary>
        /// Id
        ///</summary>
        public int Id { get; set; }
    }
    /// <summary>
    /// 删除角色请求模型
    /// </summary>
    public class RemoveSystemRoleRequestModel
    {
        ///<summary>
        /// Id
        ///</summary>
        public int Id { get; set; }
    }
    /// <summary>
    /// 查询角色列表请求模型
    /// </summary>
    public class QuerySystemRoleRequestModel : ApiBasePageRequestModel
    {
        /// <summary>
        /// 角色名称
        /// </summary>
        public string KeyWord { get; set; }
    }
    /// <summary>
    /// 查询角色详情请求模型
    /// </summary>
    public class QueryDetailSystemRoleRequestModel :ApiBaseRequestModel
    {
        ///<summary>
        /// Id
        ///</summary>
        public int Id { get; set; }
    }
}

