// <autogenerated>
//   This file was generated by T4 code generator Template.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System.Collections.Generic;
using TianYu.Core.Common.BaseViewModel;

namespace TianYu.Admin.Domain.ViewModel.Request
{
    /// <summary>
    /// 角色权限模型
    /// </summary>
    public class SystemRoleRulesRequestModel
    { 
        ///<summary>
        /// 菜单ID
        ///</summary>
        public int MenuId { get; set; }
        ///<summary>
        /// 按键ID
        ///</summary>
        public int ButtonId { get; set; }
    }
    /// <summary>
    /// 设置角色权限模型
    /// </summary>
    public class SetSystemRoleRulesRequestModel
    {
        ///<summary>
        /// 角色ID
        ///</summary>
        public int RoleId { get; set; }
        /// <summary>
        /// 角色权限集
        /// </summary>
        public IList<SystemRoleRulesRequestModel> list { get; set; }
    }

    /// <summary>
    /// 查询角色权限列表请求模型
    /// </summary>
    public class QuerySystemRoleRulesRequestModel : ApiBaseRequestModel
    {
        /// <summary>
        /// 角色ID
        /// </summary>
        public int? RoleId { get; set; }
    }
}

