// <autogenerated>
//   This file was generated by T4 code generator Template.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TianYu.Core.Common.BaseViewModel;

namespace TianYu.Admin.Domain.ViewModel.Request
{
    /// <summary>
    /// 系统账号模型
    /// </summary>
    public class SystemStaffRequestModel
    {
        ///<summary>
        /// 手机
        ///</summary>
        public string Mobile { get; set; }
        ///<summary>
        /// 电话
        ///</summary>
        public string Tel { get; set; }
        ///<summary>
        /// 邮箱
        ///</summary>
        public string Eamil { get; set; }
        ///<summary>
        /// 呢称
        ///</summary>
        [Required]
        public string NickName { get; set; }
        ///<summary>
        /// 所属部门
        ///</summary>
        [Required]
        public string SectionId { get; set; }
        /// <summary>
        /// 角色ID
        /// </summary>
        [Required]
        public List<int> RoleId { get; set; }
    }


    /// <summary>
    /// 添加系统账号请求模型
    /// </summary>
    public class AddSystemStaffRequestModel: SystemStaffRequestModel
    {
        ///<summary>
        /// 登录名称
        ///</summary>
        [Required]
        public string LoginName { get; set; }
        ///<summary>
        /// 登录密码
        ///</summary>
        //[Required]
        //public string LoginPwd { get; set; }
    }
    /// <summary>
    /// 修改系统账号请求模型
    /// </summary>
    public class UpdateSystemStaffRequestModel: SystemStaffRequestModel
    {
        ///<summary>
        /// Id
        ///</summary>
        public int Id { get; set; }
    }
    /// <summary>
    /// 删除系统账号请求模型
    /// </summary>
    public class RemoveSystemStaffRequestModel
    {
        ///<summary>
        /// Id
        ///</summary>
        [Required]
        public int Id { get; set; }
    }
    /// <summary>
    /// 查询系统账号列表请求模型
    /// </summary>
    public class QuerySystemStaffRequestModel : ApiBasePageRequestModel
    {
        /// <summary>
        /// 登录名称/呢称/手机号
        /// </summary>
        public string KeyWord { get; set; }
    }
    /// <summary>
    /// 查询系统账号详情请求模型
    /// </summary>
    public class QueryDetailSystemStaffRequestModel :ApiBaseRequestModel
    {
        /// <summary>
        /// 登录名称/呢称/手机号
        /// </summary>
        public int Id { get; set; }
    }
    /// <summary>
    /// 重置密码
    /// </summary>
    public class ResetSystemStaffRequestModel
    {
        ///<summary>
        /// Id
        ///</summary>
        [Required]
        public int Id { get; set; }
        ///<summary>
        /// 新登录密码
        ///</summary>
        [Required]
        public string NewLoginPwd { get; set; }
        /// <summary>
        /// 旧密码
        /// </summary>
        [Required]
        public string OldLoginPwd { get; set; }
    }
    /// <summary>
    /// 修改密码
    /// </summary>
    public class UpdatePwdSystemStaffRequestModel : ApiBaseRequestModel
    {
        ///<summary>
        /// 新登录密码
        ///</summary>
        [Required]
        public string NewLoginPwd { get; set; }
        /// <summary>
        /// 旧密码
        /// </summary>
        [Required]
        public string OldLoginPwd { get; set; }
    }
}

