// <autogenerated>
//   This file was generated by T4 code generator Template.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

  
using TianYu.Core.Common.BaseViewModel;

namespace TianYu.Admin.Domain.ViewModel.Request
{
    /// <summary>
    /// 账号角色模型
    /// </summary>
    public class SystemStaffRoleRequestModel
    { 
                ///<summary>
        /// ID
        ///</summary>
        public int Id { get; set; }
        ///<summary>
        /// 用户Id
        ///</summary>
        public int StaffId { get; set; }
        ///<summary>
        /// 角色Id
        ///</summary>
        public int RoleId { get; set; }
    }


    /// <summary>
    /// 添加账号角色请求模型
    /// </summary>
    public class AddSystemStaffRoleRequestModel: SystemStaffRoleRequestModel
    {

    }
    /// <summary>
    /// 修改账号角色请求模型
    /// </summary>
    public class UpdateSystemStaffRoleRequestModel: SystemStaffRoleRequestModel
    {
        ///<summary>
        /// Id
        ///</summary>
        public int Id { get; set; }
    }
    /// <summary>
    /// 删除账号角色请求模型
    /// </summary>
    public class RemoveSystemStaffRoleRequestModel
    {
        ///<summary>
        /// Id
        ///</summary>
        public int Id { get; set; }
    }
    /// <summary>
    /// 查询账号角色列表请求模型
    /// </summary>
    public class QuerySystemStaffRoleRequestModel : ApiBaseRequestModel
    {

    }
    /// <summary>
    /// 查询账号角色详情请求模型
    /// </summary>
    public class QueryDetailSystemStaffRoleRequestModel :ApiBaseRequestModel
    {

    }
}

