// <autogenerated>
//   This file was generated by T4 code generator Template.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using TianYu.Core.Common.BaseViewModel;

namespace TianYu.Admin.Domain.ViewModel.Request
{
    /// <summary>
    /// 角色权限表模型
    /// </summary>
    public class SystemRolePowerRequestModel : ApiBaseRequestModel
    {
        ///<summary>
        /// 后台角色Id
        ///</summary>
        public int RoleId { get; set; }
        ///<summary>
        /// 后台权限Id
        ///</summary>
        public int PowerId { get; set; }
    }


    /// <summary>
    /// 设置角色权限表请求模型
    /// </summary>
    public class SetSystemRolePowerRequestModel : ApiBaseRequestModel
    {
        ///<summary>
        /// 角色Id
        ///</summary>
        public int RoleId { get; set; }
        /// <summary>
        /// 权限Id
        /// </summary>
        public System.Collections.Generic.List<int> PowerIdList { get; set; }
    }
    /// <summary>
    /// 查询角色权限表列表请求模型
    /// </summary>
    public class QuerySystemRolePowerRequestModel : ApiBaseRequestModel
    {

    }
    /// <summary>
    /// 查询角色权限表详情请求模型
    /// </summary>
    public class QueryDetailSystemRolePowerRequestModel : ApiBaseRequestModel
    {

    }
}

