// <autogenerated>
//   This file was generated by T4 code generator Template.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System;
using System.ComponentModel.DataAnnotations;
using TianYu.Core.Common.BaseViewModel;

namespace TianYu.Admin.Domain.ViewModel.Request
{
    /// <summary>
    /// 部门模型
    /// </summary>
    public class SystemSectionRequestModel
    {
        ///<summary>
        /// 父级ID
        ///</summary>
        [Required]
        public int ParentId { get; set; }
        ///<summary>
        /// 部门名称
        ///</summary>
        [Required]
        public string Name { get; set; } 
        ///<summary>
        /// 部门描述
        ///</summary>
        public string Remark { get; set; }
        ///<summary>
        /// 部门负责人
        ///</summary>
        public string Person { get; set; }
        ///<summary>
        /// 排序
        ///</summary>
        public int Sort { get; set; }
        ///<summary>
        /// 是否启用
        ///</summary>
        public bool Enabled { get; set; } 
        /// <summary>
        /// 父级编码
        /// </summary>
        public int ParentCode { get; set; }
    }


    /// <summary>
    /// 添加部门请求模型
    /// </summary>
    public class AddSystemSectionRequestModel : SystemSectionRequestModel
    {

    }
    /// <summary>
    /// 修改部门请求模型
    /// </summary>
    public class UpdateSystemSectionRequestModel : SystemSectionRequestModel
    {
        ///<summary>
        /// Id
        ///</summary>
        public int Id { get; set; }
    }
    /// <summary>
    /// 删除部门请求模型
    /// </summary>
    public class RemoveSystemSectionRequestModel
    {
        ///<summary>
        /// Id
        ///</summary>
        public int Id { get; set; }
    }
    /// <summary>
    /// 查询部门列表请求模型
    /// </summary>
    public class QuerySystemSectionRequestModel : ApiBaseRequestModel
    {
        /// <summary>
        /// 部门名称
        /// </summary>
        public string KeyWord { get; set; } 
    }
    /// <summary>
    /// 查询部门详情请求模型
    /// </summary>
    public class QueryDetailSystemSectionRequestModel : ApiBaseRequestModel
    {
        ///<summary>
        /// Id
        ///</summary>
        public int Id { get; set; }
    }
}

