// <autogenerated>
//   This file was generated by T4 code generator Template.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System.ComponentModel.DataAnnotations;
using TianYu.Core.Common.BaseViewModel;

namespace TianYu.Admin.Domain.ViewModel.Request
{
    /// <summary>
    /// 菜单模型
    /// </summary>
    public class SystemMenuRequestModel
    {
        ///<summary>
        /// 菜单名称
        ///</summary>
        [Required]
        public string MenuName { get; set; }
        ///<summary>
        /// 菜单描述
        ///</summary>
        public string MenuDesc { get; set; }
        ///<summary>
        /// 菜单图标
        ///</summary>
        public string MenuIcon { get; set; }
        ///<summary>
        /// 菜单Url
        ///</summary>
        public string MenuUrl { get; set; }
        ///<summary>
        /// 父级ID(-1为顶级)
        ///</summary>
        [Required]
        public int ParentId { get; set; }
        ///<summary>
        /// 是否启用
        ///</summary>
        public bool Enabled { get; set; }
        ///<summary>
        /// 菜单按钮
        ///</summary>
        public string MenuButtonId { get; set; }
        ///<summary>
        /// 层级
        ///</summary>
        [Required]
        public int Level { get; set; }
        ///<summary>
        /// 排序
        ///</summary>
        [Required]
        public int MenuSort { get; set; } 
    }


    /// <summary>
    /// 添加菜单请求模型
    /// </summary>
    public class AddSystemMenuRequestModel: SystemMenuRequestModel
    { 
        ///<summary>
        /// 父级编码
        ///</summary>
        public int ParentCode { get; set; }
    }
    /// <summary>
    /// 修改菜单请求模型
    /// </summary>
    public class UpdateSystemMenuRequestModel: SystemMenuRequestModel
    {
        ///<summary>
        /// Id
        ///</summary>
        public int Id { get; set; }
    } 
    /// <summary>
    /// 删除菜单请求模型
    /// </summary>
    public class RemoveSystemMenuRequestModel
    {
        ///<summary>
        /// Id
        ///</summary>
        public int Id { get; set; }
    }
    /// <summary>
    /// 禁用或启用菜单请求模型
    /// </summary>
    public class EnabledSystemMenuRequestModel
    {
        ///<summary>
        /// Id
        ///</summary>
        public int Id { get; set; }
        /// <summary>
        /// 是否禁用
        /// </summary>
        public bool Enabled { get; set; }
    }
    /// <summary>
    /// 查询菜单列表请求模型
    /// </summary>
    public class QuerySystemMenuRequestModel : ApiBaseRequestModel
    {
        /// <summary>
        /// 菜单名称
        /// </summary>
        public string KeyWord { get; set; }
    }
    /// <summary>
    /// 查询菜单详情请求模型
    /// </summary>
    public class QueryDetailSystemMenuRequestModel :ApiBaseRequestModel
    {
        /// <summary>
        /// 菜单ID
        /// </summary>
        [Required]
        public int Id { get; set; }
    }
}

