// <autogenerated>
//   This file was generated by T4 code generator Template.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

 
using System;
using TianYu.Admin.Domain.BaseModel; 

namespace TianYu.Admin.Domain 
{    
    /// <summary> 
	/// 实体-角色 
	/// </summary> 
	public partial class SystemRole: AggregateRoot    
    {    
	    public SystemRole()
        {
                }

                ///<summary>
        /// Id
        ///</summary>
        public int Id { get; set; }
        ///<summary>
        /// 角色名称
        ///</summary>
        public string RoleName { get; set; }
        ///<summary>
        /// 角色编号
        ///</summary>
        public string RoleCode { get; set; }
        ///<summary>
        /// 角色描述
        ///</summary>
        public string RoleDesc { get; set; }
        ///<summary>
        /// 排序
        ///</summary>
        public int Sort { get; set; }
        ///<summary>
        /// 是否启用
        ///</summary>
        public bool Enabled { get; set; }
        ///<summary>
        /// 创建时间
        ///</summary>
        public DateTime CreateTime { get; set; }
        ///<summary>
        /// 修改时间
        ///</summary>
        public DateTime ModifyTime { get; set; }
    }
}
