// <autogenerated>
//   This file was generated by T4 code generator Template.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

 
using System;
using TianYu.Admin.Domain.BaseModel; 

namespace TianYu.Admin.Domain 
{    
    /// <summary> 
	/// 实体-账号角色 
	/// </summary> 
	public partial class SystemStaffRole: AggregateRoot    
    {    
	    public SystemStaffRole()
        {
                }
         
        /// <summary>
        /// Id
        /// </summary>
        public int Id { get; set; }
        ///<summary>
        /// 用户Id
        ///</summary>
        public int StaffId { get; set; }
        ///<summary>
        /// 角色Id
        ///</summary>
        public int RoleId { get; set; }
    }
}
