// <autogenerated>
//   This file was generated by T4 code generator Template.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System;
using TianYu.Admin.Domain.BaseModel;

namespace TianYu.Admin.Domain
{
    /// <summary> 
    /// 实体-菜单 
    /// </summary> 
    public partial class SystemMenu : AggregateRoot
    {
        public SystemMenu()
        {
        }

        ///<summary>
        /// Id
        ///</summary>
        public int Id { get; set; }
        ///<summary>
        /// 菜单名称
        ///</summary>
        public string MenuName { get; set; }
        ///<summary>
        /// 菜单描述
        ///</summary>
        public string MenuDesc { get; set; }
        ///<summary>
        /// 菜单图标
        ///</summary>
        public string MenuIcon { get; set; }
        ///<summary>
        /// 菜单Url
        ///</summary>
        public string MenuUrl { get; set; }
        ///<summary>
        /// 父级ID(-1为顶级)
        ///</summary>
        public int ParentId { get; set; }
        ///<summary>
        /// 是否启用
        ///</summary>
        public bool Enabled { get; set; }
        ///<summary>
        /// 菜单按钮
        ///</summary>
        public string MenuButtonId { get; set; }
        ///<summary>
        /// 层级
        ///</summary>
        public int? Level { get; set; }
        ///<summary>
        /// 排序
        ///</summary>
        public int MenuSort { get; set; }
        ///<summary>
        /// 创建时间
        ///</summary>
        public DateTime CreateTime { get; set; }
        ///<summary>
        /// 修改时间
        ///</summary>
        public DateTime ModifyTime { get; set; }
        ///<summary>
        /// 菜单编码
        ///</summary>
        public int MenuCode { get; set; }
        ///<summary>
        /// 父级编码
        ///</summary>
        public int? ParentCode { get; set; }
        /// <summary>
        /// 页索引
        /// </summary>
        public string PageTitle { get; set; }
    }
}
