// <autogenerated>
//   This file was generated by T4 code generator Template.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

 
using System;
using TianYu.Admin.Domain.BaseModel; 

namespace TianYu.Admin.Domain 
{    
    /// <summary> 
	/// 实体-角色权限 
	/// </summary> 
	public partial class SystemRoleRules: AggregateRoot    
    {    
	    public SystemRoleRules()
        {
                }
        /// <summary>
        /// Id
        /// </summary>
        public int Id { get; set; }
        ///<summary>
        /// 角色ID
        ///</summary>
        public int RoleId { get; set; }
        ///<summary>
        /// 菜单ID
        ///</summary>
        public int MenuId { get; set; }
        ///<summary>
        /// 按键ID
        ///</summary>
        public int ButtonId { get; set; }
    }
}
