// <autogenerated>
//   This file was generated by T4 code generator Template.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System;
using TianYu.Admin.Domain.BaseModel;

namespace TianYu.Admin.Domain
{
    /// <summary> 
    /// 实体-数据字典 
    /// </summary> 
    public partial class SystemDictionary : AggregateRoot
    {
        public SystemDictionary()
        {
        }

        ///<summary>
        /// Id
        ///</summary>
        public int Id { get; set; }
        ///<summary>
        /// 父级ID（第一级为0）
        ///</summary>
        public int ParentId { get; set; }
        ///<summary>
        /// 字典名称
        ///</summary>
        public string Name { get; set; } 
        ///<summary>
        /// 字典描述
        ///</summary>
        public string Remark { get; set; }
        ///<summary>
        /// 字典值
        ///</summary>
        public string Value { get; set; }
        ///<summary>
        /// 排序
        ///</summary>
        public int? Sort { get; set; }
        ///<summary>
        /// 创建时间
        ///</summary>
        public DateTime CreateTime { get; set; }
        ///<summary>
        /// 修改时间
        ///</summary>
        public DateTime ModifyTime { get; set; }
    }
}
