// <autogenerated>
//   This file was generated by T4 code generator Template.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

 
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TianYu.Admin.Domain.Mapping
{
    /// <summary>
    /// 系统账号实体映射类
    /// </summary>
    public partial class SystemStaffMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<TianYu.Admin.Domain.SystemStaff>
    {
        public SystemStaffMap()
        {
            // table
            ToTable("s_SystemStaff", "dbo");

			// keys
		    HasKey(t => t.Id);
	 
			// Properties
		   Property(t => t.Id)
                   .HasColumnName("Id")
                   .IsRequired();
           Property(t => t.LoginName)
                   .HasMaxLength(50)
                   .HasColumnName("LoginName")
                   .IsRequired();
           Property(t => t.LoginPwd)
                   .HasMaxLength(32)
                   .HasColumnName("LoginPwd")
                   .IsRequired();
           Property(t => t.MaskCode)
                   .HasMaxLength(32)
                   .HasColumnName("MaskCode")
                   .IsRequired();
           Property(t => t.Mobile)
                   .HasMaxLength(20)
                   .HasColumnName("Mobile")
                   .IsOptional();
           Property(t => t.Tel)
                   .HasMaxLength(20)
                   .HasColumnName("Tel")
                   .IsOptional();
           Property(t => t.Eamil)
                   .HasMaxLength(50)
                   .HasColumnName("Eamil")
                   .IsOptional();
           Property(t => t.NickName)
                   .HasMaxLength(50)
                   .HasColumnName("NickName")
                   .IsOptional();
           Property(t => t.Status)
                   .HasColumnName("Status")
                   .IsRequired();
           Property(t => t.SectionId)
                   .HasMaxLength(20)
                   .HasColumnName("SectionId")
                   .IsOptional();
           Property(t => t.LastLoginTime)
                   .HasColumnName("LastLoginTime")
                   .IsOptional();
           Property(t => t.CreateTime)
                   .HasColumnName("CreateTime")
                   .IsRequired();
           Property(t => t.ModifyTime)
                   .HasColumnName("ModifyTime")
                   .IsRequired();
		 	 
        }
    }
}

