// <autogenerated>
//   This file was generated by T4 code generator Template.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

 
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TianYu.Admin.Domain.Mapping
{
    /// <summary>
    /// 部门实体映射类
    /// </summary>
    public partial class SystemSectionMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<TianYu.Admin.Domain.SystemSection>
    {
        public SystemSectionMap()
        {
            // table
            ToTable("s_SystemSection", "dbo");

			// keys
		    HasKey(t => t.Id);
	 
			// Properties
		           Property(t => t.Id)
                   .HasColumnName("Id")
                   .IsRequired();
           Property(t => t.ParentId)
                   .HasColumnName("ParentId")
                   .IsRequired();
           Property(t => t.Name)
                   .HasMaxLength(50)
                   .HasColumnName("Name")
                   .IsRequired();
           Property(t => t.Code) 
                   .HasColumnName("Code")
                   .IsRequired();
            Property(t => t.ParentCode)
                  .HasColumnName("ParentCode")
                  .IsRequired();
            Property(t => t.Remark)
                   .HasMaxLength(50)
                   .HasColumnName("Remark")
                   .IsOptional();
           Property(t => t.Person)
                   .HasMaxLength(50)
                   .HasColumnName("Person")
                   .IsOptional();
           Property(t => t.Sort)
                   .HasColumnName("Sort")
                   .IsOptional();
           Property(t => t.Enabled)
                   .HasColumnName("Enabled")
                   .IsRequired();
           Property(t => t.CreateTime)
                   .HasColumnName("CreateTime")
                   .IsRequired();
           Property(t => t.ModifyTime)
                   .HasColumnName("ModifyTime")
                   .IsRequired();
            Property(t => t.Level)
                .HasColumnName("Level")
                .IsRequired();
        }
    }
}

