// <autogenerated>
//   This file was generated by T4 code generator Template.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

 
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TianYu.Admin.Domain.Mapping
{
    /// <summary>
    /// 角色实体映射类
    /// </summary>
    public partial class SystemRoleMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<TianYu.Admin.Domain.SystemRole>
    {
        public SystemRoleMap()
        {
            // table
            ToTable("s_SystemRole", "dbo");

			// keys
		    HasKey(t => t.Id);
	 
			// Properties
		           Property(t => t.Id)
                   .HasColumnName("Id")
                   .IsRequired();
           Property(t => t.RoleName)
                   .HasMaxLength(50)
                   .HasColumnName("RoleName")
                   .IsRequired();
           Property(t => t.RoleCode)
                   .HasMaxLength(20)
                   .HasColumnName("RoleCode")
                   .IsOptional();
           Property(t => t.RoleDesc)
                   .HasMaxLength(50)
                   .HasColumnName("RoleDesc")
                   .IsOptional();
           Property(t => t.Sort)
                   .HasColumnName("Sort")
                   .IsRequired();
           Property(t => t.Enabled)
                   .HasColumnName("Enabled")
                   .IsRequired();
           Property(t => t.CreateTime)
                   .HasColumnName("CreateTime")
                   .IsRequired();
           Property(t => t.ModifyTime)
                   .HasColumnName("ModifyTime")
                   .IsRequired();
		 	 
        }
    }
}

