// <autogenerated>
//   This file was generated by T4 code generator Template.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

 
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TianYu.Admin.Domain.Mapping
{
    /// <summary>
    /// 账号角色实体映射类
    /// </summary>
    public partial class SystemStaffRoleMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<TianYu.Admin.Domain.SystemStaffRole>
    {
        public SystemStaffRoleMap()
        {
            // table
            ToTable("s_SystemStaffRole", "dbo");

            // keys
            HasKey(t => t.Id);

            // Properties
            Property(t => t.Id)
            .HasColumnName("Id")
            .IsRequired();
            Property(t => t.StaffId)
                   .HasColumnName("StaffId")
                   .IsRequired();
           Property(t => t.RoleId)
                   .HasColumnName("RoleId")
                   .IsRequired();
		 	 
        }
    }
}

