// <autogenerated>
//   This file was generated by T4 code generator Template.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

 
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TianYu.Admin.Domain.Mapping
{
    /// <summary>
    /// 数据字典实体映射类
    /// </summary>
    public partial class SystemDictionaryMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<TianYu.Admin.Domain.SystemDictionary>
    {
        public SystemDictionaryMap()
        {
            // table
            ToTable("s_SystemDictionary", "dbo");

			// keys
		    HasKey(t => t.Id);
	 
			// Properties
		           Property(t => t.Id)
                   .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity)
                   .HasColumnName("Id")
                   .IsRequired();
           Property(t => t.ParentId)
                   .HasColumnName("ParentId")
                   .IsRequired(); 
            Property(t => t.Name)
                  .HasMaxLength(50)
                  .HasColumnName("Name")
                  .IsRequired();
            Property(t => t.Remark)
                   .HasMaxLength(1000)
                   .HasColumnName("Remark")
                   .IsOptional();
           Property(t => t.Value)
                   .HasColumnName("Value")
                   .IsOptional();
           Property(t => t.Sort)
                   .HasColumnName("Sort")
                   .IsOptional();
           Property(t => t.CreateTime)
                   .HasColumnName("CreateTime")
                   .IsRequired();
           Property(t => t.ModifyTime)
                   .HasColumnName("ModifyTime")
                   .IsRequired();
		 	 
        }
    }
}

